export const EMPLOYEES_SET = 'EMPLOYEES_SET';
export const EMPLOYEE_EDIT = 'EMPLOYEE_EDIT';
export const EMPLOYEE_DELETE = 'EMPLOYEE_DELETE';
export const EMPLOYEE_ADD = 'EMPLOYEE_ADD';

export const REVIEWS_SET = 'REVIEWS_SET';

export const SERVICES_SET = 'SERVICES_SET';